package org.sayar.net.General.enums;

public enum DashboardAccessEnum {
    MANAGER_DASHBOARD_HIGHEST_PRIORITY_WORK_ORDER,
    MANAGER_DASHBOARD_HIGH_PRIORITY_WORK_ORDER,
    MANAGER_DASHBOARD_AVERAGE_PRIORITY_WORK_ORDER,
    MANAGER_DASHBOARD_LOW_PRIORITY_WORK_ORDER,
    MANAGER_DASHBOARD_LOWEST_PRIORITY_WORK_ORDER,
    MANAGER_DASHBOARD_OPEN_WORK_ORDER,
    MANAGER_DASHBOARD_CLOSED_WORK_ORDER,
    MANAGER_DASHBOARD_PENDING_WORK_ORDER,
    MANAGER_DASHBOARD_DRAFT_WORK_ORDER,
    MANAGER_DASHBOARD_OVER_DUE_WORK_ORDER,
    MANAGER_DASHBOARD_HIGHEST_PRIORITY_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_HIGH_PRIORITY_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_AVERAGE_PRIORITY_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_LOW_PRIORITY_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_LOWEST_PRIORITY_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_OPEN_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_CLOSED_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_PENDING_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_DRAFT_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_OVER_DUE_PLANNED_WORK_ORDER,
    MANAGER_DASHBOARD_PLANNED_WORK_ORDER_RATIO,
    GENERAL_ACTIVE_ASSET,
    GENERAL_IN_ACTIVE_ASSET
}
