package org.sayar.net.Enumes;

public enum AccessList {
    user_create ,
    user_delete ,
    user_edit ,
    user_detail ,
    post_create ,
    post_delete ,
    post_edit ,
    post_detail ,
    province_create ,
    province_delete ,
    province_edit ,
    city_create ,
    city_delete ,
    city_edit ,
    org_create ,
    org_delete ,
    org_edit ,
    org_detail ,
    category_create ,
    category_delete ,
    category_edit ,
    category_detail ,
    tools_create ,
    tools_delete ,
    tools_edit ,
    tools_detail ,
    machinery_create ,
    machinery_delete ,
    machinery_edit ,
    machinery_detail ,
    facility_create ,
    facility_delete ,
    facility_edit ,
    facility_detail,
    formBuilder_create,
    formBuilder_delete,
    formBuilder_edit,
    formBuilder_detail,
    processBuilder_create,
    processBuilder_delete,
    processBuilder_edit,
    processBuilder_detail,
    metering_detail,
    metering_create,
    privateMessage_detail,
    privateMessage_delete,
    senderMessage_detail,
    senderMessage_delete,
    systemMessage_detail,
    systemMessage_delete,
    message_send,
    myAssets_detail,
    myAssets_edit,
    myParts_detail,
    myParts_edit,
    myWorkOrders_detail,
    myWorkOrders_edit,
    organization_detail,
    organization_create,
    organization_edit,
    organization_delete,
    workRequest_detail,
    workRequest_delete,
    workRequest_create,


}
