package org.sayar.net.Enumes;

public enum ResponseKeyWord {

    OK,
    FAILURE,
    SC_UNAUTHORIZED,
    USEREXISTS,
    INVALIDE_USERNAME_OR_PASSWORD,
    UNAUTHORIZED,
    ACESSDENIDE,
    TOKEN_EXPIRE,
    USER_NOT_NOTFOUND,
    USER_TYPE_NOTFOUND,
    USER_SIGNUPDED,
    INFORMATION_LOSE,
    ERROR_IN_UPLOAD_FILE,
    ORGAN_NULL,
    FILE_NOT_FOUND,
    USER_DONT_HAVE_IMAGE,
    DATABASE_ERROR,
    CAN_NOT_DELETE,
    FIRST_SIGN_IN,
    INVALID_INPUT
}
